apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret-from-vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: PS_BDD_DB
      remoteRef:
        key: let-note
        property: PS_BDD_DB
    - secretKey: PS_BDD_USER
      remoteRef:
        key: let-note
        property: PS_BDD_USER
    - secretKey: PS_BDD_PASS
      remoteRef:
        key: let-note
        property: PS_BDD_PASS
    - secretKey: POSTGRES_DB
      remoteRef:
        key: let-note
        property: PS_BDD_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: let-note
        property: PS_BDD_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: let-note
        property: PS_BDD_PASS
    - secretKey: JWT_SECRET
      remoteRef:
        key: let-note
        property: JWT_SECRET
    - secretKey: COOKIE_SECURE
      remoteRef:
        key: let-note
        property: COOKIE_SECURE
