apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  VAULT_LOCAL_CONFIG: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:18200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/data"
    }

    api_addr = "https://vault.127.0.0.1.nip.io"
    cluster_addr = "http://vault.vault.svc.cluster.local:18201"
