apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: let-note
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: prod
  template:
    metadata:
      name: "let-note-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/laflut3/let-note.git
        targetRevision: main
        path: infrastructure/deploiement-kube/charts/let-note
        helm:
          releaseName: "let-note-{{env}}"
          valueFiles:
          - "environments/{{env}}.yaml"
          parameters:
          - name: secrets.create
            value: "false"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
