apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: let-note-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laflut3/let-note.git
    targetRevision: main
    path: infrastructure/deploiement-kube/environments/dev
    kustomize:
      images:
      - ghcr.io/laflut3/let-note-backend:__IMAGE_TAG__
      - ghcr.io/laflut3/let-note-frontend:__IMAGE_TAG__
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
