apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: let-note-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laflut3/let-note.git
    targetRevision: main
    path: infrastructure/deploiement-kube/helm/let-note
    helm:
      releaseName: let-note-staging
      valueFiles:
      - environments/staging.yaml
      parameters:
      - name: images.backend.tag
        value: __IMAGE_TAG__
      - name: images.frontend.tag
        value: __IMAGE_TAG__
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
