apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweed-master
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweed-volume
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweed-filer
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweed-s3
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
