apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
  - ../../base/vault
secretGenerator:
  - name: vault-auth
    literals:
      - token=REPLACE_WITH_VAULT_TOKEN
generatorOptions:
  disableNameSuffixHash: true
