apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  VAULT_LOCAL_CONFIG: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/data"
    }

    api_addr = "http://vault.vault.svc.cluster.local:8200"
    cluster_addr = "http://vault.vault.svc.cluster.local:8201"
