apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PS_BDD_DB: let_note_staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  APP_ENV: staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: let_note_staging
