apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ include "let-note.namespace" . }}
  labels:
    {{- include "let-note.commonLabels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ include "let-note.namespace" . }}
  labels:
    {{- include "let-note.commonLabels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.seaweedfs.size | quote }}
