global:
  environment: prod

config:
  frontend:
    APP_ENV: prod
  app:
    env: prod
    routes:
      frontendBaseUrl: https://let-note.prod.polydo.dev
      backendBaseUrl: https://let-note.prod.polydo.dev/api
    ingress:
      host: let-note.prod.polydo.dev
    cors:
      allowedOrigins:
        - https://let-note.prod.polydo.dev

postgres:
  database: let_note_prod

secrets:
  create: false

backend:
  replicas: 1
  vault:
    secretPath: prod/let-note
    k8sRole: let-note-prod
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi

frontend:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi

ingress:
  host: let-note.prod.polydo.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
