global:
  environment: staging

config:
  frontend:
    APP_ENV: staging
  app:
    env: staging
    routes:
      frontendBaseUrl: http://staging.app.local
      backendBaseUrl: http://staging.app.local/api
    ingress:
      host: staging.app.local
    cors:
      allowedOrigins:
        - http://localhost:5173
        - http://127.0.0.1:5173
        - http://staging.app.local

postgres:
  database: let_note_staging

backend:
  replicas: 2
  vault:
    secretPath: staging/let-note
    k8sRole: let-note-staging
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi

frontend:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi

ingress:
  host: staging.app.local
