apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: VAULT_SECRET_PATH
          value: let-note/dev
