apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  APP_ENV: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app-config.yaml: |
    app:
      name: let-note
      env: prod
    routes:
      frontend_base_url: https://let-note.polydo.dev
      backend_base_url: https://let-note.polydo.dev/api
      health_path: /api/health
      auth:
        login_path: /api/auth/login
        logout_path: /api/auth/logout
    ingress:
      host: let-note.polydo.dev
      frontend_path: /
      api_path: /api
    cors:
      allowed_origins:
        - https://let-note.polydo.dev
