apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PS_BDD_SERVER: postgres
  PS_BDD_PORT: "5432"
  PS_BDD_DB: let_note_dev
  PS_BDD_USER: let_note
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  APP_ENV: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: let_note_dev
  POSTGRES_USER: let_note
