apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  PS_BDD_DB: "${PS_BDD_DB}"
  PS_BDD_USER: "${PS_BDD_USER}"
  PS_BDD_PASS: "${PS_BDD_PASS}"
  POSTGRES_DB: "${PS_BDD_DB}"
  POSTGRES_USER: "${PS_BDD_USER}"
  POSTGRES_PASSWORD: "${PS_BDD_PASS}"
  JWT_SECRET: "${JWT_SECRET}"
  COOKIE_SECURE: "${COOKIE_SECURE}"
