apiVersion: v1
kind: Secret
metadata:
  name: vault-app-auth
type: Opaque
stringData:
  token: "${VAULT_APP_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_ME_STRONG_DB_PASSWORD_DEV
